# Generated by Django 2.2.3 on 2021-11-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='person',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='person',
            new_name='teacher',
        ),
    ]
